[package]
name = "bitar"
version = "0.6.2"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "bita archive utilities"
repository = "https://github.com/oll3/bita"
readme = "README.md"
keywords = ["sofware-update", "file-synchronization", "delta-update",  "differential"]
categories = ["compression", "filesystem"]


[build-dependencies]
prost-build = "0.6"

[dependencies]
blake2 = "0.8"
blake3 = "0.3"
prost = "0.6"
log = "0.4"
brotli = "3.3"
futures-core = "0.3"
futures-util = "0.3"
tokio = "0.2"
async-stream = "0.2"
bytes = "0.5"
rust-lzma = { version = "0.5", optional = true }
zstd = { version = "0.5", optional = true }
async-trait = "0.1"
num_cpus = "1.13"

[dev-dependencies]
tempfile = "3.1"
tokio = {version = "0.2", features = ["fs", "macros"] }

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["stream"]

[features]
default-tls = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]
lzma-compression = ["rust-lzma"]
zstd-compression = ["zstd"]
